[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true



ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[fuzz]
runs = 10000

[fmt]
line_length = 140
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
arbitrum_rpc = "${ARBITRUM_RPC_URL}"
arbitrum_sepolia_rpc = "${ARBITRUM_SEPOLIA_RPC_URL}"

[etherscan]
arbiscan = {key = "${ARBISCAN_API_KEY}", chain = 42161 }
arbsepoliascan = {key = "${ARBISCAN_API_KEY}", chain = 421614 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


